name = "GeoAcceleratedArrays"
uuid = "a1bd0a3b-d31e-42b9-ba04-538dc10eeccf"
authors = ["Maarten Pronk", "Deltares"]
version = "0.2.0"

[deps]
AcceleratedArrays = "44e12807-9a19-5591-91cf-c1b4fb89ce64"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LibSpatialIndex = "f19c2e90-9d16-5f2d-a2a7-af3fb29e4907"

[compat]
AcceleratedArrays = "0.3"
Extents = "0.1"
GeoInterface = "1"
LibSpatialIndex = "0.2"
julia = "1.6"

[extras]
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LibGEOS"]
