name = "GeoAcceleratedArrays"
uuid = "a1bd0a3b-d31e-42b9-ba04-538dc10eeccf"
authors = ["Maarten Pronk", "Deltares"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
